//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _MP22NET__201091___DONG_RongYu___HEBUT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public int Id { get; set; }
        public string DishName { get; set; }
        public decimal Money { get; set; }
    }
}
