//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _MP22NET__201091___DONG_RongYu___HEBUT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiters
    {
        public Waiters()
        {
            this.RestaurantMap = new HashSet<RestaurantMap>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public decimal EarnedMoney { get; set; }
        public int HandledTable { get; set; }
    
        public virtual ICollection<RestaurantMap> RestaurantMap { get; set; }
    }
}
